package nuts.commerce.inventoryservice.model

enum class EventType {
    RESERVATION_CREATION_SUCCEEDED,
    RESERVATION_CREATION_FAILED,
    RESERVATION_CONFIRM_SUCCEEDED,
    RESERVATION_CONFIRM_FAILED,
    RESERVATION_RELEASE_SUCCEEDED,
    RESERVATION_RELEASE_FAILED
}