package nuts.commerce.inventoryservice.model

enum class EventType {
    RESERVATION_CREATION,
    RESERVATION_COMMITTED,
    RESERVATION_RELEASED,
    RESERVE_INVENTORY_REQUEST,
    RESERVE_INVENTORY_CONFIRM,
    RESERVE_INVENTORY_RELEASE
}