package nuts.commerce.paymentservice.model

enum class EventType {
    PAYMENT_CREATION_SUCCEEDED,
    PAYMENT_CREATION_FAILED,
    PAYMENT_CONFIRM_SUCCEEDED,
    PAYMENT_CONFIRM_FAILED,
    PAYMENT_RELEASE_SUCCEEDED,
    PAYMENT_RELEASE_FAILED
}