package nuts.commerce.inventoryservice.event

enum class EventType {
    STOCK_UPDATE,
    RESERVATION_COMMITTED,
    RESERVATION_RELEASED,
    RESERVE_INVENTORY_REQUEST,
    RESERVE_INVENTORY_CONFIRM,
    RESERVE_INVENTORY_RELEASE
}
